### ISSUE TITLE
metadata.json needs to have image height & width in quotes

### ISSUE THREAD

**Issue by rajannpatel** [ageitgey/amplify#16]
Your issue is in [metadata.json](https://github.com/ageitgey/amplify/blob/master/_includes/metadata.json)

Test against a [`structured page validator`](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fcdn.ampproject.org%2Fc%2Fs%2Fageitgey.github.io%2Famplify%2F2016%2F03%2F08%2Fexample-post.html)

Worth noting the correct structure should be:
`    "height": "60",
    "width": "60"
  `

You are missing quotes.

**Comment by ageitgey** [comment]
Thanks, fixed in #18
