### ISSUE TITLE
invalid HTML <time> datetime format

### ISSUE THREAD

**Issue by jbspeakr** [ageitgey/amplify#22]
Currently, in the post-meta in `index.html` the value of the <time> datetime is set through `{{ post.date | date_to_long_string }}`. That leads to something like this: `<time datetime="01 February 2017">`

However, the HTML <time> tag requires a datetime in ISO8601 format (`YYYY-MM-DDThh:mm:ssTZD`) - [see W3C](https://www.w3schools.com/TagS/att_time_datetime.asp), e.g.: `<time datetime="2017-02-01T08:00">`

That could be solved by using `{{ post.date | date_to_xmlschema }}`. I'll open a PR.

**Comment by ageitgey** [comment]
Thanks. Merged.
