### ISSUE TITLE
8s of doom

### ISSUE THREAD

**Issue by zorker** [ageitgey/amplify#4]
Wth?

    <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>

**Comment by ageitgey** [comment]
I'm not sure what your question is, but it sounds like it's a question for the amp team. This is part of the amp boilerplate provided by them.

Check out the amphtml project there: https://github.com/ampproject/amphtml/blob/master/spec/amp-boilerplate.md.

**Comment by zorker** [comment]
It makes the page go blank for 8 seconds onload. Not sure if you want that to happen to any website that you call amplified.

**Comment by ageitgey** [comment]
It doesn't go blank on any device I've tried. If you are seeing that, you should report a bug to the amphtml project and let them know the browser/device you saw it on.
