### ISSUE TITLE
Errors with jekyll-paginate

### ISSUE THREAD

**Issue by wilsonmar** [ageitgey/amplify#5]
After I clone and bundle, I'm getting this message when I try to jekyll-serve:

```
Configuration file: /Users/mac/gits/jekyll/amplify/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.2 | Error:  jekyll-paginate
```

I notice the _config.xml file contains:
```
gem:
   - jekyll-paginate
```
Perhaps this is related to jekyll-paginate being deprecated in Jekyll v3:
https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004/18

My system status:

```
ruby -v
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin15.3.0]
jekyll-3.1.2
```

**Comment by sergimiral** [comment]
@wilsonmar same here, and yes it seems like a deprecation related issue – I could run jekyll-serve with no problems after installing jekyll-paginate manually with

`gem install jekyll-paginate`

**Comment by ageitgey** [comment]
I updated the installation instructions in the README to add this step:

*Step 3:* Run `gem install bundler; bundle install` inside the new `/amplify/` folder that was 
just created to install the required ruby dependencies.

That should fix it for you. Thanks!

**Comment by alexwidener** [comment]
Unfortunately, neither the solution to install jekyll-paginate manually nor the updated instructions work for me. I have the same error posted above.

    jekyll 3.1.2
    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    node v5.7.0

ruby(&gems) were installed with brew, then jekyll was installed through gem.
node was installed with brew as well.

**Comment by alexwidener** [comment]
{ageitgey}/{amplify}#9
